### ISSUE TITLE
Cannot correctly install python requirements.

### ISSUE THREAD

**Issue by GDHNES** [noise-lab/NetDiffusion_Generator#1]
When trying to install requirements with the CLI command`pip install -r requirements`, I got 

```
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```
 

Then I check the requirements.txt file, and found some comments saying
" \# This file may be used to create an environment using:
\# $ conda create --name <env> --file <this file>
\# platform: linux-64 ...".
I tried install a whole-new virtual environment with` conda create --name net-diffusion --file requirements.txt`, unfortunately it failed again.

The fail message was:

```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pygments==2.17.2=pypi_0
  - ca-certificates==2023.12.12=h06a4308_0
  - importlib-resources==6.1.1=pypi_0
  - lit==17.0.6=pypi_0
  - nvidia-cusparse-cu11==11.7.4.91=pypi_0
  - jinja2==3.1.3=pypi_0
  - aiosignal==1.3.1=pypi_0
  - python-multipart==0.0.9=pypi_0
  - nvidia-cuda-nvrtc-cu11==11.7.99=pypi_0
  - wandb==0.15.11=pypi_0
  - coloredlogs==15.0.1=pypi_0
  - opt-einsum==3.3.0=pypi_0
  - tqdm==4.66.2=pypi_0
  - opencv-python==4.7.0.68=pypi_0
  - cycler==0.12.1=pypi_0
  - nvidia-nvjitlink-cu12==12.3.101=pypi_0
  - zipp==3.17.0=pypi_0
  - sentry-sdk==1.40.5=pypi_0
  - pyparsing==3.1.1=pypi_0
  - cachetools==5.3.2=pypi_0
  - appdirs==1.4.4=pypi_0
  - onnxruntime-gpu==1.16.0=pypi_0
  - nvidia-cublas-cu11==11.10.3.66=pypi_0
  - tzdata==2023d=h04d1e81_0
  - requests-oauthlib==1.3.1=pypi_0
  - setuptools==68.2.2=py310h06a4308_0
  - certifi==2024.2.2=py310h06a4308_0
  - numexpr==2.8.7=py310h85018f9_0
  - tbb==2021.8.0=hdb19cb5_0
  - xformers==0.0.21=pypi_0
  - blas==1.0=mkl
  - sympy==1.12=pypi_0
  - smmap==5.0.1=pypi_0
  - wheel==0.41.2=py310h06a4308_0
  - h5py==3.10.0=pypi_0
  - packaging==23.2=pypi_0
  - importlib-metadata==7.0.1=pypi_0
  - gast==0.5.4=pypi_0
  - libwebp-base==1.3.2=h5eee18b_0
  - astunparse==1.6.3=pypi_0
  - oauthlib==3.2.2=pypi_0
  - fsspec==2024.2.0=pypi_0
  - markdown==3.5.1=pypi_0
  - numpy-base==1.26.3=py310hb5e798b_0
  - numpy==1.26.1=pypi_0
  - nvidia-cuda-runtime-cu12==12.1.105=pypi_0
  - libclang==16.0.6=pypi_0
  - tensorboard-data-server==0.7.2=pypi_0
  - libpng==1.6.39=h5eee18b_0
  - rsa==4.9=pypi_0
  - sqlite==3.41.2=h5eee18b_0
  - transformers==4.36.2=pypi_0
  - markdown-it-py==2.2.0=pypi_0
  - docker-pycreds==0.4.0=pypi_0
  - mpmath==1.3.0=pypi_0
  - frozenlist==1.4.1=pypi_0
  - diffusers==0.25.0=pypi_0
  - absl-py==2.0.0=pypi_0
  - attrs==23.2.0=pypi_0
  - ffmpy==0.3.2=pypi_0
  - bottleneck==1.3.7=py310ha9d4c09_0
  - setproctitle==1.3.3=pypi_0
  - grpcio==1.59.2=pypi_0
  - pip==23.3.1=py310h06a4308_0
  - freetype==2.12.1=h4a9f257_0
  - tensorboard==2.14.1=pypi_0
  - mkl-service==2.4.0=py310h5eee18b_1
  - safetensors==0.4.2=pypi_0
  - anyio==4.3.0=pypi_0
  - antlr4-python3-runtime==4.9.3=pypi_0
  - libgcc-ng==11.2.0=h1234567_1
  - nvidia-cufft-cu12==11.0.2.54=pypi_0
  - pydantic==2.6.1=pypi_0
  - _libgcc_mutex==0.1
  - yarl==1.9.4=pypi_0
  - gradio==3.50.2=pypi_0
  - libuuid==1.41.5=h5eee18b_0
  - orjson==3.9.14=pypi_0
  - pytz==2023.3.post1=py310h06a4308_0
  - ml-dtypes==0.2.0=pypi_0
  - omegaconf==2.3.0=pypi_0
  - uvicorn==0.27.1=pypi_0
  - altair==4.2.2=pypi_0
  - nvidia-cudnn-cu12==8.9.2.26=pypi_0
  - charset-normalizer==3.3.2=pypi_0
  - pathtools==0.1.2=pypi_0
  - pytorch-lightning==1.9.0=pypi_0
  - starlette==0.36.3=pypi_0
  - ftfy==6.1.1=pypi_0
  - httpx==0.27.0=pypi_0
  - fairscale==0.4.13=pypi_0
  - jpeg==9e=h5eee18b_1
  - nvidia-nvtx-cu11==11.7.91=pypi_0
  - tensorflow-estimator==2.14.0=pypi_0
  - toml==0.10.2=pypi_0
  - markupsafe==2.1.3=pypi_0
  - lz4-c==1.9.4=h6a678d5_0
  - torchmetrics==1.3.1=pypi_0
  - pydub==0.25.1=pypi_0
  - triton==2.2.0=pypi_0
  - tensorflow-io-gcs-filesystem==0.34.0=pypi_0
  - nvidia-cublas-cu12==12.1.3.1=pypi_0
  - prodigyopt==1.0=pypi_0
  - google-auth==2.23.4=pypi_0
  - nvidia-nccl-cu12==2.19.3=pypi_0
  - libffi==3.4.4=h6a678d5_0
  - onnx==1.14.1=pypi_0
  - huggingface-hub==0.20.1=pypi_0
  - websockets==11.0.3=pypi_0
  - openjpeg==2.4.0=h3ad879b_0
  - pandas==2.1.4=py310h1128e8f_0
  - scapy==2.5.0=pypi_0
  - nvidia-nccl-cu11==2.14.3=pypi_0
  - openssl==1.1.1w=h7f8727e_0
  - annotated-types==0.6.0=pypi_0
  - gitpython==3.1.42=pypi_0
  - six==1.16.0=pyhd3eb1b0_1
  - rich==13.4.1=pypi_0
  - toolz==0.12.1=pypi_0
  - ncurses==6.4=h6a678d5_0
  - lightning-utilities==0.10.1=pypi_0
  - _openmp_mutex==5.1=1_gnu
  - exceptiongroup==1.2.0=pypi_0
  - gradio-client==0.6.1=pypi_0
  - tensorrt-bindings==8.6.1=pypi_0
  - pillow==10.2.0=py310h5eee18b_0
  - tensorrt-libs==8.6.1=pypi_0
  - tensorrt==8.6.1.post1=pypi_0
  - lcms2==2.12=h3be6417_0
  - entrypoints==0.4=pypi_0
  - readline==8.2=h5eee18b_0
  - ld_impl_linux-64==2.38=h1181459_1
  - flatbuffers==23.5.26=pypi_0
  - termcolor==2.3.0=pypi_0
  - aiohttp==3.9.3=pypi_0
  - libgomp==11.2.0=h1234567_1
  - werkzeug==3.0.1=pypi_0
  - sentencepiece==0.2.0=pypi_0
  - httpcore==1.0.4=pypi_0
  - easygui==0.98.3=pypi_0
  - async-timeout==4.0.3=pypi_0
  - nvidia-cuda-cupti-cu11==11.7.101=pypi_0
  - xz==5.4.5=h5eee18b_0
  - mdurl==0.1.2=pypi_0
  - pyasn1-modules==0.3.0=pypi_0
  - kiwisolver==1.4.5=pypi_0
  - google-auth-oauthlib==1.0.0=pypi_0
  - nvidia-cusparse-cu12==12.1.0.106=pypi_0
  - aiofiles==23.2.1=pypi_0
  - pyyaml==6.0.1=pypi_0
  - wrapt==1.14.1=pypi_0
  - google-pasta==0.2.0=pypi_0
  - nvidia-cufft-cu11==10.9.0.58=pypi_0
  - multidict==6.0.5=pypi_0
  - mkl_random==1.2.4=py310hdb19cb5_0
  - referencing==0.33.0=pypi_0
  - typing-extensions==4.8.0=pypi_0
  - jsonschema-specifications==2023.12.1=pypi_0
  - python-tzdata==2023.3=pyhd3eb1b0_0
  - tensorflow==2.14.0=pypi_0
  - tokenizers==0.15.2=pypi_0
  - nvidia-cuda-nvrtc-cu12==12.1.105=pypi_0
  - accelerate==0.25.0=pypi_0
  - filelock==3.13.1=pypi_0
  - matplotlib==3.8.3=pypi_0
  - nvidia-cuda-runtime-cu11==11.7.99=pypi_0
  - voluptuous==0.13.1=pypi_0
  - libdeflate==1.17=h5eee18b_1
  - h11==0.14.0=pypi_0
  - einops==0.6.1=pypi_0
  - nvidia-cusolver-cu11==11.4.0.1=pypi_0
  - lion-pytorch==0.0.6=pypi_0
  - nvidia-cusolver-cu12==11.4.5.107=pypi_0
  - rpds-py==0.18.0=pypi_0
  - python==3.10.9=h7a1cb2a_2
  - fonttools==4.49.0=pypi_0
  - python-dateutil==2.8.2=pyhd3eb1b0_0
  - idna==3.4=pypi_0
  - pywavelets==1.5.0=pypi_0
  - mkl==2023.1.0=h213fc3f_46344
  - networkx==3.2.1=pypi_0
  - humanfriendly==10.0=pypi_0
  - nvidia-cudnn-cu11==8.5.0.96=pypi_0
  - urllib3==2.0.7=pypi_0
  - click==8.1.7=pypi_0
  - contourpy==1.2.0=pypi_0
  - jsonschema==4.21.1=pypi_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - nvidia-nvtx-cu12==12.1.105=pypi_0
  - requests==2.31.0=pypi_0
  - invisible-watermark==0.2.0=pypi_0
  - nvidia-curand-cu11==10.2.10.91=pypi_0
  - bzip2==1.0.8=h7b6447c_0
  - pyasn1==0.5.0=pypi_0
  - keras==2.14.0=pypi_0
  - zlib==1.2.13=h5eee18b_0
  - mkl_fft==1.3.8=py310h5eee18b_0
  - fastapi==0.109.2=pypi_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - torch==2.2.0=pypi_0
  - semantic-version==2.10.0=pypi_0
  - libtiff==4.5.1=h6a678d5_0
  - sniffio==1.3.0=pypi_0
  - wcwidth==0.2.13=pypi_0
  - psutil==5.9.8=pypi_0
  - nvidia-cuda-cupti-cu12==12.1.105=pypi_0
  - zstd==1.5.5=hc292b87_0
  - lycoris-lora==2.0.2=pypi_0
  - dadaptation==3.1=pypi_0
  - pydantic-core==2.16.2=pypi_0
  - nvidia-curand-cu12==10.3.2.106=pypi_0
  - protobuf==3.20.3=pypi_0
  - regex==2023.12.25=pypi_0
  - cmake==3.28.3=pypi_0
  - tk==0.1.0=pypi_0
  - lerc==3.0=h295c915_0
  - bitsandbytes==0.41.1=pypi_0
  - scipy==1.11.4=pypi_0
  - gitdb==4.0.11=pypi_0

Current channels:

  - https://conda.anaconda.org/default/linux-64
  - https://conda.anaconda.org/default/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Is there any other way to get things done? Could you double check the `requirements.txt` file?

**Comment by arielgoes** [comment]
Hello, I faced the same issue over the last days. After reading a lot, I found out these requirements are in a PIP formata, not conda. I managed to do everything with Python environment.

First, you must clone both [kohya_ss_fork @ 8a39d4d](https://github.com/Chasexj/kohya_ss_fork/tree/8a39d4dc1b7410d38a1373e490b2261af6a6ac27) and [sd-webui-fork @ 2533cf8](https://github.com/Chasexj/stable-diffusion-webui-fork/tree/2533cf84cad7313b8653717d15728a2d9a862c15) inside [fine_tune](https://github.com/noise-lab/NetDiffusion_Generator/tree/main/fine_tune)

Then, you run `./setup.sh` (this file is inside [kohya_ss_fork @ 8a39d4d](https://github.com/Chasexj/kohya_ss_fork/tree/8a39d4dc1b7410d38a1373e490b2261af6a6ac27))

The setup will install all the requirements inside a Python 3.10.13 environment. After that, I advise to run everything with the virtual environment:
```
cd <NetDiffusion main folder>/fine_tune/kohya_ss_fork/
source venv/bin/activate
```

Example output:
`(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ `

Also, make sure the bitsandbytes pip module is working already. Check it with `python -m bitsandbytes` (WITHIN THE VIRTUAL ENVIRONMENT):
```
(venv) (base) thiago@ifsuldeminas-Z390-M-GAMING:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ python -m bitsandbytes
False

===================================BUG REPORT===================================
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/thiago/anaconda3 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda-11.8/lib64')}
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: :/usr/local//cuda-11.8/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
(venv) (base) thiago@ifsuldeminas-Z390-M-GAMING:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_((v(v(venv) (base) thiago@ifsuldeminas-Z390-M-GAMING:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ssfor_fork$ 
```

I spent days looking for the fix. I only needed to correctly support the library path for CUDA. Make sure you have the correct CUDA set to `LD_LIBRARY_PATH`:

1. Verify which cuda version utilized by PyTorch in the virtual environment:
```
(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ python
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'11.8'
>>> exit()
(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$
``` 

2.  Find where is `libducadart.so` it (if any):
```
(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ find / -name libcudart.so 2>/dev/null
/home/caio/miniconda3/envs/tf/lib/libcudart.so
/home/caio/miniconda3/pkgs/cuda-cudart-dev-12.2.53-0/lib/libcudart.so
/home/caio/miniconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so
/home/thiago/anaconda3/envs/ydata/lib/libcudart.so
/home/thiago/anaconda3/pkgs/cuda-cudart-dev-12.1.105-0/lib/libcudart.so
/home/thiago/anaconda3/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/lib/libcudart.so
/home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so
/home/caue/anaconda3/envs/myenv/lib/libcudart.so
/home/caue/anaconda3/pkgs/cuda-cudart-dev-12.4.99-0/lib/libcudart.so
(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ 
```
In my case, the correct one should be like this:
`export LD_LIBRARY_PATH=/home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib`

Note: don't do this:
`export LD_LIBRARY_PATH=/home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so`

4. Now, check again if bitsandbytes is working already:
```
(venv) (base) user@user:~/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork$ python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/thiago/anaconda3/lib/libicudata.so
/home/thiago/anaconda3/envs/ydata/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/thiago/anaconda3/envs/ydata/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/thiago/anaconda3/envs/ydata/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/home/thiago/anaconda3/envs/ydata/lib/libcudart.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.12_cuda11.8_cudnn8.7.0_0/lib/python3.12/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.12_cuda11.8_cudnn8.7.0_0/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.12_cuda11.8_cudnn8.7.0_0/lib/python3.12/site-packages/torch/lib/libc10_cuda.so
/home/thiago/anaconda3/pkgs/cuda-cudart-dev-12.1.105-0/lib/libcudart.so
/home/thiago/anaconda3/pkgs/icu-58.2-he6710b0_3/lib/libicudata.so
/home/thiago/anaconda3/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/lib/libcudart.so
/home/thiago/anaconda3/pkgs/icu-73.1-h6a678d5_0/lib/libicudata.so
/home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so
/home/thiago/anaconda3/pkgs/llvm-openmp-18.1.1-h4dfa4b3_0/lib/libomptarget.rtl.cuda.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.10_cuda11.8_cudnn8.7.0_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.10_cuda11.8_cudnn8.7.0_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/thiago/anaconda3/pkgs/pytorch-2.2.1-py3.10_cuda11.8_cudnn8.7.0_0/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/thiago/git_ariel/NetDiffusion_Generator/fine_tune/kohya_ss_fork/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 /home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib CUDA PATHS 
/home/thiago/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['7.5']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

**Comment by Bozolzr** [comment]
Thanks！Really helped me a lot！

**Comment by GDHNES** [comment]
Thank you for your detailed reply, it works for me as well!  Maybe removing the misleading comment in the `requirements.txt` or a few tweaks for the installation part would keep people out of this pitfall. :-)
